// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//       >
//         {children}
//       </body>
//     </html>
//   );
// }





import './globals.css'
import { Metadata } from 'next'
import Header from '../components/Header'
import Hero from '@/components/Hero'
// import BannerGrid from '@/components/BannerGrid'
import Footer from '../components/Footer'
import { Roboto } from 'next/font/google'
import Categories from '@/components/Categories'
import GoodLooksSection from '@/components/GoodLookSection'
import WinterSection from '@/components/WinterSection'
import AmericanEagleBanner from '@/components/AmericanEagleBanner'
import Lakme from '@/components/Lakme'
import GstBanner from '@/components/GstBanner'
import ExploreBrands from '@/components/ExploreBrands'
import ExtraBanner from '@/components/ExtraBanner'
const roboto = Roboto({ subsets: ['latin'], weight: ['300','400','500','700'], variable: '--font-roboto' })



export const metadata: Metadata = {
title: 'Lifestyle Clone - Demo',
description: 'Next.js + Tailwind front-end clone (demo)'
}


export default function RootLayout({ children }: { children: React.ReactNode }) {
return (
  <html lang="en" className={roboto.variable}>
    <body className="bg-white text-gray-800 scroll-smooth bg-yellow-50/70">
      <Header />
      <main>
        {children}
        <Hero />
        <Categories />
        <GoodLooksSection />
        <WinterSection />
        <GstBanner />
        <ExtraBanner />
        {/* <ExploreBrands />
        <Lakme /> */}
        <AmericanEagleBanner />

      {/* <BannerGrid /> */}
      {/* <CategoryCard /> */}
      {/* <ProductGrid /> */}

      </main>
      <Footer />
    </body>
  </html>
  )
  }